### PR TITLE
Test files added

### PR DESCRIPTION
**Pull request by teeseng**

### CODE REVIEW

**Comment by Domanic** [comment]
Can you please remove "README" from your PR?

**Comment by teeseng** [comment]
Hi removed README in a proposed change.

**Comment by Domanic** [comment]
Your pull request still has "README". Sorry if I wasn't clear, what I meant is your pull request shouldn't touch README, it should only add the 4 files. Can you please fix it?

**Comment by teeseng** [comment]
Okay, it looks like it is fixed. Sorry for the trouble!

**Pull request merged**
