### PR TITLE
adding tests for ecb2344

### PR DESCRIPTION
**Pull request by ebigelow12**

### CODE REVIEW

**Comment by Domanic** [comment]
Can you please remove "*RunLife.c++" and include "*RunLife.in" instead?

**Comment by ebigelow12** [comment]
I fixed the files as you requested. Let me know if you have any more issues.

**Comment by Domanic** [comment]
Looks like "*RunLife.c++" is still there, are you sure you removed it?

**Comment by ebigelow12** [comment]
I hope this actually fixes it. I could have sworn I deleted the RunLife.c++ file when I uploaded the RunLife.in. I hope this works, let me know if you need anything else, I will be checking my email often today.

**Pull request merged**
