### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by jtlnguyen-utexas**

### CODE REVIEW

**Comment by Domanic** [comment]
You only have the initial grids in your RunLife.out. Did you commit the wrong file?

**Comment by jtlnguyen-utexas** [comment]
Just added the correct files

**Comment by Domanic** [comment]
Your acceptance test outputs don't seem correct. Do you want to take another look?

**Comment by jtlnguyen-utexas** [comment]
I was not able to complete the last acceptance test in time. The first 4 should be correct though.

**Pull request merged**
