### PR TITLE
jed2922 tests

### PR DESCRIPTION
**Pull request by javierdlg**

### CODE REVIEW

**Comment by Domanic** [comment]
Hey, I know it's weird but your acceptance tests must be the same as Prof. Downing's tests, you can simply copy that file. So your output should be the output of those tests.

**Comment by javierdlg** [comment]
got it updating in a few

**Comment by javierdlg** [comment]
By acceptance tests do you mean Tests.out or runLife.out?

**Comment by Domanic** [comment]
I mean RunLife.in/out

**Pull request closed without merging**
