### PR TITLE
Test files for bds2477 and zrd227

### PR DESCRIPTION
**Pull request by zaldaroga**

### CODE REVIEW

**Comment by Domanic** [comment]
Your acceptance test outputs don't seem correct. Do you want to take another look?

**Comment by zaldaroga** [comment]
@Domanic We were unsure how many points submitting late was worth compared to correcting the output. Can you please let us know?

**Comment by Domanic** [comment]
We haven't decided the exact penalty for incorrect output. But I'd say it's worth fixing your code and submitting late, if you can do it in 1 day.

**Comment by zaldaroga** [comment]
Ok we will try. We have been struggling on this same problem for a while now but we will try to get it in by tomorrow night.

**Comment by zaldaroga** [comment]
@Domanic We fixed it. Thanks!

**Comment by Domanic** [comment]
Great! But can you fix the filenames so there's only one EID, the EID of the repo owner, in the file names?

**Comment by zaldaroga** [comment]
@Domanic Done!

**Pull request merged**
